version: "3"
services:
  php-fpm:
    build: .
    container_name: app
    restart: always
    volumes:
      - ./:/var/www
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: cash-transfer
      POSTGRES_USER: cash-transfer
      POSTGRES_PASSWORD: cash-transfer
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  nginx:
    build: ./.docker/nginx
    container_name: web-server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cash-transfer
      MONGO_INITDB_ROOT_PASSWORD: cash-transfer
    ports:
      - "27017:27017"
