version: "3"
services:
  postgres:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: cash-transfer
      POSTGRES_USER: cash-transfer
      POSTGRES_PASSWORD: cash-transfer
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  nginx:
    image: nginx:alpine
    container_name: web-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: ./.docker/php
    container_name: app
    restart: always
    volumes:
      - ./:/var/www
